image: archlinux
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~reykjalin/vscode-kakoune
tasks:
  - setup: |
      cd vscode-kakoune
      npm ci
      npm run build
  - test: |
      cd vscode-kakoune
      # npm test
